apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: golang-api
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed   
  resources:
    requests:
      storage: 5Gi
